export const MUTATION_LOGIN = 'auth/MUTATION_LOGIN'
export const MUTATION_LOGOUT = 'auth/MUTATION_LOGOUT'
export const MUTATION_TOKEN_FROM_LOCAL_STORAGE = 'auth/MUTATION_TOKEN_FROM_LOCAL_STORAGE'

export const ACTION_LOGIN = 'auth/ACTION_LOGIN'
export const ACTION_LOGOUT = 'auth/ACTION_LOGOUT'
export const ACTION_TOKEN_FROM_LOCAL_STORAGE = 'auth/ACTION_TOKEN_FROM_LOCAL_STORAGE'
export const ACTION_REFRESH_TOKEN = 'auth/ACTION_REFRESH_TOKEN'